### PR TITLE
Freezer

### PR DESCRIPTION
**Pull request by Battery-not-included**

### CODE REVIEW

**Comment by dromer** [comment]
Hey, I see two issues with your patch:

1. you are trying to access a table called `cache02` but this doesn't exist anywhere.
2. the tables in the patch are saving their data, this shouldn't be necessary since you are just using them as a buffer and not as a preloaded sample (they contain all 0's so are completely silent anyway)

To fix 1. make sure you either add this table or use the correct name that you intend. For 2. disable the `Save contents` option when saving the patch.

**Review by Battery-not-included — COMMENTED** [review]
Hope now it will be ok.

**Comment by dromer** [comment]
Builds succeed at least!

My only comment would be on the patch itself as it is very hard to read, but it's your code so you can maintain it how you like ;)

**Comment by falkTX** [comment]
lets get things moving again, merging this now.

sorry for the very long delay, company stuff was happening and a whole lot of complications. but now slowly resuming operations and everything back again.

**Comment by falkTX** [comment]
Reminder for myself: need to add a way to do custom ttl from this repo.

though there is now an alternative with us starting to package some hvcc based plugins, for example https://github.com/mod-audio/mod-plugin-builder/blob/master/plugins/package/sensorium-plugins/sensorium-plugins.mk
it doesnt require to push files to this repo, but still requires a repo nonetheless.

we can also store the pd files directly in mod-plugin-builder together with the mk file like the one in the link above, but that complicated things for the case of custom ttl because it then needs to go into a separate repo and being kept in sync...

@Battery-not-included would you prefer to keep pushing files to this repo and we help with reviewing things, or handle the git repo yourself?

**Comment by Battery-not-included** [comment]
Hi, for now it is better for me to put the file in this repository. By the way I see the changes in the cloud builder for pd where the option for multiple files is added, with that it is now possible to use abstraction and midi functions, nice update thanks.

**Comment by falkTX** [comment]
@Battery-not-included I was going to start integrating the custom ttl, so I grabbed the latest one you have on the forums, the duox build https://drive.google.com/file/d/1iZlF7ehbDHOfX4KgUIjOYjAsy0zGGNeZ/view?usp=drive_link

but that custom ttl does not match the pd file we have here.

Here is the diff between the custom ttl and the one generated by dpf:

```diff
--- Freezer_dsp.ttl	2024-10-11 11:32:35.609500453 +0200
+++ _Freezer_dsp.ttl	2024-10-11 11:32:35.612500560 +0200
@@ -57,22 +57,42 @@
         lv2:index 3 ;
         lv2:name "attack" ;
         lv2:symbol "attack" ;
-        lv2:default 500 ;
+        lv2:default 100 ;
         lv2:minimum 0 ;
         lv2:maximum 2000 ;
     ] ,
     [
         a lv2:InputPort, lv2:ControlPort ;
         lv2:index 4 ;
+        lv2:name "current step" ;
+        lv2:symbol "current_step" ;
+        lv2:default 1 ;
+        lv2:minimum 1 ;
+        lv2:maximum 6 ;
+        lv2:portProperty lv2:integer ;
+    ] ,
+    [
+        a lv2:InputPort, lv2:ControlPort ;
+        lv2:index 5 ;
         lv2:name "decay" ;
         lv2:symbol "decay" ;
-        lv2:default 500 ;
+        lv2:default 100 ;
         lv2:minimum 0 ;
         lv2:maximum 2000 ;
     ] ,
     [
         a lv2:InputPort, lv2:ControlPort ;
-        lv2:index 5 ;
+        lv2:index 6 ;
+        lv2:name "decay x10" ;
+        lv2:symbol "decay_x10" ;
+        lv2:default 1 ;
+        lv2:minimum 1 ;
+        lv2:maximum 10 ;
+        lv2:portProperty lv2:toggled ;
+    ] ,
+    [
+        a lv2:InputPort, lv2:ControlPort ;
+        lv2:index 7 ;
         lv2:name "dry" ;
         lv2:symbol "dry" ;
         lv2:default 1 ;
@@ -81,26 +101,63 @@
     ] ,
     [
         a lv2:InputPort, lv2:ControlPort ;
-        lv2:index 6 ;
+        lv2:index 8 ;
         lv2:name "freeze" ;
         lv2:symbol "freeze" ;
         lv2:default 0 ;
         lv2:minimum 0 ;
         lv2:maximum 1 ;
-        lv2:portProperty lv2:toggled ;
+        lv2:portProperty lv2:toggled , mod:preferMomentaryOnByDefault ;
     ] ,
     [
         a lv2:InputPort, lv2:ControlPort ;
-        lv2:index 7 ;
+        lv2:index 9 ;
+        lv2:name "layers number" ;
+        lv2:symbol "layers_number" ;
+        lv2:default 1 ;
+        lv2:minimum 1 ;
+        lv2:maximum 6 ;
+        lv2:portProperty lv2:integer ;
+    ] ,
+    [
+        a lv2:InputPort, lv2:ControlPort ;
+        lv2:index 10 ;
+        lv2:name "layers volume" ;
+        lv2:symbol "layers_volume" ;
+        lv2:default 0.8 ;
+        lv2:minimum 0 ;
+        lv2:maximum 1 ;
+    ] ,
+    [
+        a lv2:InputPort, lv2:ControlPort ;
+        lv2:index 11 ;
         lv2:name "mode" ;
         lv2:symbol "mode" ;
         lv2:default 0 ;
         lv2:minimum 0 ;
         lv2:maximum 1 ;
     ] ,
     [
         a lv2:InputPort, lv2:ControlPort ;
-        lv2:index 8 ;
+        lv2:index 12 ;
+        lv2:name "sample length" ;
+        lv2:symbol "sample_length" ;
+        lv2:default 1 ;
+        lv2:minimum 0.2 ;
+        lv2:maximum 1 ;
+    ] ,
+    [
+        a lv2:InputPort, lv2:ControlPort ;
+        lv2:index 13 ;
         lv2:name "speed" ;
         lv2:symbol "speed" ;
         lv2:default 1 ;
@@ -109,7 +166,7 @@
     ] ,
     [
         a lv2:InputPort, lv2:ControlPort ;
-        lv2:index 9 ;
+        lv2:index 14 ;
         lv2:name "wet" ;
         lv2:symbol "wet" ;
         lv2:default 1 ;
```

Since your duox custom ttl has more parameters, I imagine you have since tweaked the pd file for it.
Is this the case? if so please update the pd file on this repo to your latest version, thanks!

**Comment by Battery-not-included** [comment]
Yeah, I have a newer version on the forum. I will be updating the PD file there.

**Comment by falkTX** [comment]
it is best if we keep things centralized here, we need to have the files in here in order to do builds anyhow.

**Comment by Battery-not-included** [comment]
sorry i mean here not there :) i will update pd file here.

**Comment by Battery-not-included** [comment]
Does it work now? I have updated it in my Forks and I don't know if this is the right way.

**Pull request merged**
